In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(np.arange(10)) #arange function

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
l=range(1000)
%timeit [i**2 for i in l]

In [ ]:
a=np.arange(1000)
%timeit a**2

# Creating numpy array.
##  ==> 1D array is Vector.
##  ==> 2D array is Matrix.
##  ==> nD array is Tensor.

In [ ]:
# 1D array
a=np.array([1,2,3,4,5,7,6,7])
print(a)
print(a.ndim) #prints dimension of array a .
print(a.shape) #says it have 8 elements
len(a)

In [ ]:
# 2D array
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(b.ndim,"It is dimension of array")
print(b.shape,"It is shape of array 2 rows and 4 column")
len(b)

In [ ]:
# 3D array
c=np.array([[[1,2,3],[3,4,5]],[[5,6,6],[7,8,9]]])
print(c)
print(c.ndim,"It is dimension of array")
print(c.shape,"It is shape of array ")
len(c)

# Functions for creating arrays.

In [ ]:
# arange is an arrayed-valued version of built-in python range function
a = np.arange(10)
print(a)
b = np.arange(1,20,2)
print(b)

In [ ]:
#using linspace
a = np.linspace(1,20,10) #last one is number of points
print(a)

In [ ]:
#common arrays


In [ ]:
ar1 =np.array([[1,2,3],[4,5,6],[7,8,9]])
ar1[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
ar1=np.array([2.3,4,5,6,7])
ar2=np.array([1,2,3,4,5])
ar1.astype(ar2.dtype)

In [ ]:
ar1=np.array([2.3,4,5,6,7])

np.ones_like(ar1)

In [ ]:
ar1=np.array((1,2,3,4))

ar1

In [ ]:
list1=[5,6,7,8]
ar3=np.array(list1)
ar3[1]=0
list1

In [ ]:
ar1=np.array([1,2,3,4])

ar1

In [ ]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

In [ ]:
ar4=np.array(ar1,copy=False)
ar4[0]=-1
ar1

#array([-1,  2,  3,  4])

In [ ]:
ar1=np.zeros(5)
ar1

In [ ]:
ar1=np.ones((3,5),dtype=float)
ar1

In [ ]:
ar1=3*np.arange(8)
ar1

In [ ]:
import numpy as np
ar1=3*np.arange(8)

print(ar1[:4:])
print(ar1[::4])
print(ar1[4::4])
print(len(ar1[4:]) )
print(ar1[4:4:])

[0 3 6 9]
[ 0 12]
[12]
4
[]
